
version: '3.8'
services:
  discovery-server:
    container_name: discovery-server
    image: discovery-server:1.0
    build:
      context: .
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
 ### Zookeeper Service (Requerido para Kafka)
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  ### Kafka Service

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.1
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper


