
version: '3.8'
services:
  discovery-server:
    container_name: discovery-server
    image: discovery-server:1.0
    build:
      context: .
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
